pup-dashboard:
  image: pupscan/dashboard:latest
  container_name: dashboard
  restart: unless-stopped
  ports:
    - 80:5000
  links:
    - crawler:crawler
  environment:
    - TZ=Europe/Paris

crawler:
  image: pupscan/dashboard-crawler:latest
  container_name: crawler
  restart: unless-stopped
  environment:
    - TZ=Europe/Paris  
